
(function(){
  const isEN=()=>document.documentElement.lang==='en';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const normalize=s=>(s||'').replace(/\s+/g,' ').trim();

  const kpiES=[
   [/^Unidades educativas$/,['Número de establecimientos educativos incluidos en la información educativa vinculada al CPV 2024.','Se cuentan las UE que cumplen los filtros territoriales activos. UE significa “unidad educativa”.','Es un conteo de establecimientos registrados; no equivale necesariamente al número de edificios físicos.']],
   [/^Estudiantes matriculados$/,['Total del campo «Número de Estudiantes» de las UE seleccionadas.','Se suman los valores de «Número de Estudiantes» de cada UE incluida por los filtros. El total nacional disponible es 2.851.742.','Esta matrícula no proviene del Censo de Población y Vivienda 2024 (CPV 2024). La información disponible no documenta institución productora, gestión escolar ni fecha de corte; por eso se presenta como matrícula incluida en la información educativa vinculada al CPV 2024, separada de la población censal.']],
   [/^UE con área clasificada$/,['UE cuya comunidad asociada tiene una clasificación utilizable como Rural o Urbana.','Se cuenta una UE cuando el campo de área de su comunidad asociada es «RURAL» o «URBANO».','La clasificación se refiere a la comunidad asociada a la UE, no necesariamente a una clasificación independiente del establecimiento.']],
   [/^UE sin clasificación de área$/,['UE cuyo campo de área de la comunidad asociada aparece como «SIN RELACION».','Se cuentan las UE con ese valor en el campo de área usado por el filtro. A nivel nacional son 82.','No significa “UE sin ubicación” ni “UE sin localidad identificada”. Significa únicamente que ese campo no permite clasificar la comunidad asociada como rural o urbana.']],
   [/^Localidades disponibles$/,['Número de localidades y comunidades registradas en la información territorial y demográfica del CPV 2024 que quedan después de aplicar los filtros.','Se cuentan las localidades y comunidades registradas en el campo «Ciudad y/o comunidad» de la información territorial y demográfica del CPV 2024 dentro de la selección actual.','Una registro territorial puede representar una ciudad, pueblo, localidad o comunidad; por eso el indicador no debe leerse como un registro administrativo exclusivo de comunidades.']],
   [/^Coinciden con la búsqueda$/,['Cantidad de localidades o comunidades cuyo nombre coincide con el texto buscado.','Se aplica la búsqueda dentro del territorio ya filtrado y se cuentan las coincidencias.','Sirve para encontrar lugares; no modifica la definición censal de cada registro territorial.']],
   [/^Población del territorio$/,['Número de personas censadas en el territorio seleccionado.','Se suman los habitantes de todas las registros territoriales censales incluidas por los filtros.','Es población residente del Censo de Población y Vivienda 2024 (CPV 2024), no matrícula ni número de hogares.']],
   [/^Población de 5[–-]17 años$/,['Personas que tenían entre 5 y 17 años cumplidos en el censo.','Se suman las edades simples desde 5 hasta 17, inclusive.','Es un grupo demográfico para describir edades relacionadas con el ciclo escolar; no equivale a estudiantes matriculados ni a asistencia escolar.']],
   [/^Localidades y comunidades$/,['Conteo conjunto de las registros territoriales del campo «Ciudad y/o comunidad». La fuente reúne en el mismo campo ciudades, pueblos, localidades y comunidades.','Se cuenta cada localidad o comunidad registrada en la información territorial y demográfica del CPV 2024 una sola vez dentro del filtro.','“Localidad” se usa aquí como término amplio para un lugar poblado nombrado. “Comunidad” es una denominación territorial más específica, frecuente en áreas rurales. Como la información no contiene una variable consistente que permita separar todos los tipos, el dashboard los informa conjuntamente.']],
   [/^Municipios con registros$/,['Número de municipios o TIOC que tienen al menos una localidad o comunidad registrada en la información territorial y demográfica del CPV 2024 en la selección.','Se cuentan códigos municipales distintos presentes en los datos filtrados.','TIOC significa Territorio Indígena Originario Campesino; cuando aparece en la estructura territorial se mantiene la denominación disponible en la fuente.']],
   [/^Mediana por localidad$/,['La mediana describe el tamaño de una localidad o comunidad registrada en la información territorial y demográfica del CPV 2024 “central” sin dejar que las grandes ciudades dominen el resultado.','Se ordenan todas las localidades por población y se toma el valor del centro. Si la mediana es 92, la mitad de las registros territoriales tiene 92 habitantes o menos y la otra mitad 92 o más.','No es el promedio y no significa que la persona boliviana típica viva en una localidad de 92 habitantes. Mide el tamaño típico de las localidades y comunidades registradas en la información territorial y demográfica del CPV 2024, no la experiencia del habitante promedio.']],
   [/^Ciudades >100\.000$/,['Número de localidades registradas en la información territorial y demográfica del CPV 2024 con más de 100.000 habitantes.','Se cuentan las localidades cuya población supera el umbral analítico de 100.000.','El corte de 100.000 se usa para separar asentamientos muy grandes en algunos gráficos; no constituye una categoría administrativa oficial.']],
   [/^Edad mediana$/,['Edad que divide a la población en dos mitades.','Se acumula la población por edad hasta alcanzar el 50 % del total.','Si la edad mediana fuera 27, aproximadamente la mitad de la población tendría 27 años o menos y la otra mitad 27 o más.']],
   [/^Índice de envejecimiento$/,['Compara la población de 65 años o más con la población menor de 15 años.','Fórmula: (población de 65+ ÷ población de 0–14) × 100.','Un valor de 27,5 significa 27,5 personas de 65 años o más por cada 100 menores de 15. No significa que 27,5 % de la población sea adulta mayor.']],
   [/^Dependencia demográfica$/,['Relaciona las edades generalmente dependientes con la población en edades centrales de actividad.','Fórmula: ((0–14) + (65+)) ÷ (15–64) × 100.','Un valor de 60 significa que hay 60 personas de 0–14 o 65+ por cada 100 personas de 15–64. Es una relación demográfica, no una medición de dependencia económica individual.']],
   [/^Razón de masculinidad$/,['Número de hombres por cada 100 mujeres.','Fórmula: hombres ÷ mujeres × 100.','100 indica igual número de hombres y mujeres; más de 100 indica más hombres; menos de 100, más mujeres.']]
  ];
  const kpiEN=[
   [/^Schools$/,['Number of education establishments included in the integrated education información.','Schools that meet the active territorial filters are counted.','This is a count of recorded establishments; it is not necessarily a count of separate physical buildings.']],
   [/^Enrolled students$/,['Total of the “Number of Students” field for the selected schools.','The “Number of Students” values are added across all schools included by the filters. The available national total is 2,851,742.','These enrolment figures do not come from the 2024 Population and Housing Census. The received información does not document the producing institution, school year or reference date, so the dashboard keeps them separate from census population.']],
   [/^Schools with area classification$/,['Schools whose associated community can be classified as Rural or Urban.','A school is counted when the associated-community area field is “RURAL” or “URBANO”.','The classification refers to the community associated with the school, not necessarily to an independent classification of the school itself.']],
   [/^Schools without area classification$/,['Schools whose associated-community area field is “SIN RELACION”.','Schools with that value in the field used by the area filter are counted. There are 82 nationally.','This does not mean “school without a location” or “school without an identified locality”. It only means this field cannot classify the associated community as rural or urban.']],
   [/^Available localities$/,['Number of territorial rows remaining after the filters are applied.','Rows in the census field “City and/or community” are counted inside the current selection.','A row may represent a city, town, locality or community, so this is not an administrative register of legally defined communities.']],
   [/^Matches the search$/,['Number of locality/community names matching the search text.','The search is applied within the already filtered territory and matching rows are counted.','It helps find places; it does not change the census definition of each row.']],
   [/^Population of the territory$/,['Number of people counted by the census in the selected territory.','Population is summed across all census rows included by the filters.','This is resident population from the 2024 Population and Housing Census, not enrolment or households.']],
   [/^Population aged 5[–-]17$/,['People aged 5 through 17 at the census reference date.','Single-year ages 5 to 17 are summed, inclusive.','This is a demographic group related to school ages; it is not the number enrolled or attending school.']],
   [/^Localities and communities$/,['Combined count of rows in the “City and/or community” field. The source uses one field for cities, towns, localities and communities.','Each territorial row is counted once inside the active filter.','“Locality” is used here as a broad term for a named populated place. “Community” is a more specific territorial label, common in rural areas. Because the source does not consistently identify every type, the dashboard reports them together.']],
   [/^Municipalities with records$/,['Number of municipalities or Indigenous Native Peasant Territories (TIOC) with at least one territorial row in the selection.','Distinct municipality codes are counted in the filtered data.','The count describes geographic coverage of the data, not municipal population size.']],
   [/^Median per locality$/,['The median describes the size of the middle territorial row without letting very large cities dominate the result.','All locality rows are ordered by population and the middle value is taken. If the median is 92, half of the rows have 92 residents or fewer and half have 92 or more.','It is not the average and does not mean that the typical Bolivian person lives in a place of 92 residents. It describes the typical row, not the typical person.']],
   [/^Cities >100,000$/,['Number of territorial rows with more than 100,000 residents.','Rows above the analytical threshold of 100,000 residents are counted.','The threshold is used to separate very large settlements in some charts; it is not an official administrative category.']],
   [/^Median age$/,['Age that divides the population into two equal halves.','Population is accumulated by age until 50% of the total is reached.','If the median age were 27, roughly half the population would be age 27 or younger and half age 27 or older.']],
   [/^Ageing index$/,['Compares people aged 65+ with people under age 15.','Formula: (population 65+ ÷ population 0–14) × 100.','A value of 27.5 means 27.5 people aged 65+ for every 100 people under 15. It does not mean that 27.5% of the total population is older.']],
   [/^Demographic dependency$/,['Relates younger and older age groups to the population aged 15–64.','Formula: ((0–14) + (65+)) ÷ (15–64) × 100.','A value of 60 means 60 people aged 0–14 or 65+ for every 100 people aged 15–64. It is a demographic ratio, not an individual measure of economic dependency.']],
   [/^Sex ratio$/,['Number of men per 100 women.','Formula: men ÷ women × 100.','100 means equal numbers of men and women; above 100 means more men; below 100 means more women.']]
  ];

  const cards={
   'Matrícula por municipio + puntos de UE': ['Combina dos capas: el color del municipio resume los estudiantes registrados y los puntos muestran la ubicación de UE con coordenadas.','Para cada municipio se suman los valores del campo «Número de Estudiantes». Los puntos proceden de las coordenadas de las UE; cuando hay demasiados, se reduce únicamente su representación visual.','Un color más intenso significa mayor matrícula registrada dentro de la vista. Los totales usan todas las UE, aunque no todos los puntos se dibujen.'],
   'Enrolment by municipality + school points': ['Combines two layers: municipal colour summarises recorded students and points show georeferenced schools.','“Number of Students” is summed by municipality. School coordinates create the point layer; when points are very dense, only the visual display is thinned.','A darker/intense colour means more recorded enrolment within the current view. Totals still use all schools even when not every point is drawn.'],
   'Municipios con más matrícula':['Ordena los municipios por la suma de estudiantes registrada en la información educativa vinculada al CPV 2024.','Se agregan los estudiantes de todas las UE de cada municipio y luego se ordenan de mayor a menor.','Compara magnitudes absolutas. Un municipio grande puede aparecer arriba simplemente porque concentra más población y más establecimientos.'],
   'Municipalities with the highest enrolment':['Ranks municipalities by the student total recorded in the education información.','Student counts are summed across schools within each municipality and then ranked.','These are absolute totals. A large municipality may rank high simply because it has more people and schools.'],
   'Municipios: población 5–17 y matrícula':['Compara dos cantidades distintas para dar contexto territorial: residentes de 5–17 años y estudiantes registrados.','El eje de población usa el Censo de Población y Vivienda 2024 (CPV 2024). El eje de matrícula usa la información educativa vinculada al CPV 2024. Cada punto representa un municipio.','La diagonal indica igualdad numérica, no “cobertura”. Las dos variables tienen universos y fechas de referencia potencialmente diferentes.'],
   'Municipalities: population aged 5–17 and enrolment':['Compares two different quantities for territorial context: residents aged 5–17 and recorded students.','The population axis uses the 2024 Population and Housing Census. The enrolment axis uses the integrated education información. Each point is a municipality.','The diagonal means numerical equality, not “coverage”. The variables may have different populations and reference dates.'],
   'Dependencia de las unidades educativas':['Muestra cómo se distribuyen las UE según su dependencia registrada: Fiscal, Convenio o Privada.','Se cuenta el número de UE de cada categoría dentro de los filtros activos.','Compara establecimientos, no estudiantes. Una categoría con más UE no necesariamente concentra la misma proporción de matrícula.'],
   'School administrative type':['Shows how schools are distributed by recorded administrative type: Public, Agreement-based or Private.','Schools are counted in each category within the active filters.','This compares establishments, not students. A category with more schools does not necessarily have the same share of enrolment.'],
   'UE con localidad identificada':['UE cuya comunidad declarada pudo relacionarse de forma única con una localidad o comunidad de la información territorial y demográfica del CPV 2024 dentro del mismo municipio.','Se normaliza el nombre de la comunidad y se busca una única coincidencia territorial dentro del municipio.','El vínculo permite mostrar juntas características de la UE y de la localidad censal; no cambia los totales nacionales de UE o matrícula.'],
   'Schools with an identified locality':['Schools whose declared community could be uniquely linked to a census row within the same municipality.','The community name is normalised and a unique territorial match is sought within the municipality.','The link allows school and census-locality information to be viewed together; it does not change national school or enrolment totals.'],
   'UE sin localidad identificada':['UE para las que no se obtuvo una coincidencia única con una localidad o comunidad registrada en la información territorial y demográfica del CPV 2024.','Puede ocurrir por nombres repetidos, diferencias de escritura o ausencia de una coincidencia única dentro del municipio.','No significa que la UE no tenga ubicación. La UE continúa incluida en los totales de establecimientos y matrícula; simplemente no se le asigna una localidad o comunidad específica registrada en la información territorial y demográfica del CPV 2024.'],
   'Schools without an identified locality':['Schools for which no unique match to a census locality/community row was obtained.','This may result from repeated names, spelling differences or the lack of one unique match within the municipality.','It does not mean that the school has no location. The school remains in school and enrolment totals; it simply has no unique census-row link.'],
   'Encontrar y comparar':['Herramienta para localizar una ciudad, pueblo, localidad o comunidad por nombre dentro del territorio filtrado.','La búsqueda compara el texto escrito con los nombres disponibles en el campo «Ciudad y/o comunidad».','Usa también municipio y departamento para distinguir lugares con nombres iguales.'],
   'Find and compare':['Tool for finding a city, town, locality or community by name inside the filtered territory.','The search text is matched against names in the “City and/or community” field.','Use municipality and department as well to distinguish places that share the same name.'],
   'Ficha de la comunidad':['Resume los datos censales de la localidad o comunidad registrada en la información territorial y demográfica del CPV 2024 seleccionada.','Muestra población, sexo, edades y ubicación administrativa tal como están asociados a esa registro territorial.','La palabra “comunidad” en esta ficha se usa por continuidad de la fuente; la registro territorial también puede corresponder a otro tipo de localidad.'],
   'Locality profile':['Summarises census data for the selected territorial row.','It displays population, sex, ages and administrative location associated with that row.','The source field can contain a city, town, locality or community; the profile should be read as a territorial-row profile.'],
   'Mapa de unidades educativas vinculadas':['Muestra las UE que pudieron relacionarse con la localidad seleccionada y que tienen coordenadas utilizables.','Se filtran las UE por el vínculo territorial construido y se representan sus coordenadas.','La ausencia de un punto no prueba ausencia de oferta educativa: puede faltar una coordenada o un vínculo único.'],
   'Map of linked schools':['Shows schools that could be linked to the selected locality and have usable coordinates.','Schools are filtered using the constructed territorial link and their coordinates are plotted.','No point does not prove that no school exists: coordinates or a unique linkage may be missing.'],
   'Distribución territorial':['Resume cómo se distribuye la población entre las categorías territoriales mostradas en la vista.','Los valores se suman para cada categoría dentro de los filtros. Cuando se usa el total oficial urbano/rural, el texto lo identifica expresamente.','Compara proporciones y magnitudes; verifica siempre si la clasificación corresponde al tabulado oficial o a la clasificación de localidades.'],
   'Territorial distribution':['Summarises how population is distributed across the territorial categories shown in the view.','Values are summed for each category within the active filters. When official urban/rural totals are used, the text says so explicitly.','Compare shares and magnitudes, and note whether the classification is official or locality-based.'],
   'Territorios con más población':['Ordena los territorios por población censada.','Se suma la población de las registros territoriales pertenecientes a cada territorio y se ordena de mayor a menor.','Es un ranking de tamaño poblacional absoluto, no de densidad, crecimiento o bienestar.'],
   'Territories with the largest population':['Ranks territories by census population.','Population is summed across rows belonging to each territory and ranked from largest to smallest.','This is an absolute population ranking, not density, growth or wellbeing.'],
   'Edades de interés':['Resume grupos de edad útiles para interpretar primera infancia, edades escolares, juventud, adultez y envejecimiento.','Se suman las edades simples que pertenecen a cada grupo.','Los grupos son analíticos: facilitan la lectura, pero no prueban matrícula, asistencia, empleo ni condición de dependencia.'],
   'Age groups of interest':['Summarises age groups useful for reading early childhood, school ages, youth, adulthood and ageing.','Single-year ages belonging to each group are added together.','These are analytical groups: they support interpretation but do not prove enrolment, attendance, employment or dependency status.'],
   'Mapa de distribución':['Representa espacialmente el indicador seleccionado. Cada tono corresponde a un rango de valores.','Los territorios se ordenan y dividen en cuantiles; los tonos más oscuros representan valores mayores dentro de la vista actual.','Los colores permiten comparar posiciones relativas. Para conocer el valor exacto, usa la leyenda, el cursor o la tabla asociada.'],
   'Distribution map':['Maps the selected indicator. Each shade represents a range of values.','Territories are ordered and divided into quantiles; darker shades mean higher values within the current view.','Colours show relative position. Use the legend, hover text or associated table for exact values.'],
   'Municipios por población':['Tabla ordenada de municipios según población.','Se suman los habitantes de las localidades de cada municipio y se ordenan de mayor a menor.','Sirve para comparar tamaño demográfico. No mide superficie ni densidad poblacional.'],
   'Municipalities by population':['Table ranking municipalities by population.','Residents of locality rows within each municipality are summed and ranked.','Use it to compare demographic size. It does not measure land area or population density.'],
   'Concentración fuera de grandes ciudades':['Muestra cuánta población se concentra en las localidades de hasta 100.000 habitantes, dejando las ciudades mayores separadas.','Primero se excluyen las localidades de más de 100.000 habitantes. Las restantes se ordenan de mayor a menor. Eje X = porcentaje acumulado de localidades; eje Y = porcentaje acumulado de la población de ese grupo.','Ejemplo: si al 10 % de localidades el eje Y marca 62 %, ese 10 % de localidades más grandes reúne 62 % de la población del grupo analizado. Una curva más alejada de la diagonal indica mayor concentración.'],
   'Concentration outside large cities':['Shows how population is concentrated among localities of up to 100,000 residents, with larger cities shown separately.','Rows above 100,000 are first excluded. The rest are ordered largest to smallest. X-axis = cumulative share of localities; Y-axis = cumulative share of population in that group.','Example: if the curve is at 62% when X is 10%, the largest 10% of localities contain 62% of the population in this group. Greater distance from the diagonal means greater concentration.'],
   'Tamaño de las localidades':['Cuenta cuántas localidades y comunidades registradas en la información territorial y demográfica del CPV 2024 existen en cada rango de población.','Cada localidad se asigna a un rango según su número de habitantes y luego se cuenta cuántas localidades o comunidades pertenecen a ese rango.','La altura de una barra indica número de lugares, no número de habitantes. Un rango puede tener muchas localidades pequeñas pero una fracción reducida de población.'],
   'Size of localities':['Counts how many territorial rows fall into each population-size range.','Each locality is assigned to a range based on residents, then rows in the range are counted.','Bar height means number of places, not number of people. A range may contain many small localities but a small share of population.'],
   'Población por edad simple':['Muestra cuántas personas hay en cada edad cumplida.','Se suman, para cada edad, todas las personas de las localidades y comunidades seleccionadas de la información territorial y demográfica del CPV 2024.','Busca picos, caídas y cambios entre cohortes. La franja 5–17 sólo destaca un grupo analítico relacionado con edades escolares.'],
   'Population by single year of age':['Shows how many people are at each completed age.','For each age, people are summed across all selected territorial rows.','Look for peaks, drops and cohort changes. The 5–17 band only highlights an analytical school-age-related group.'],
   'Población en edad escolar':['Muestra la proporción y el número de residentes de 5 a 17 años.','Se suman edades 5–17 y se comparan con la población total del territorio.','Describe estructura por edad. No es tasa de escolarización ni número de estudiantes matriculados.'],
   'School-age population':['Shows the number and share of residents aged 5–17.','Ages 5–17 are summed and compared with total territorial population.','It describes age structure. It is not an enrolment rate or the number of enrolled students.'],
   'Población por grupos de edad':['Agrupa edades individuales en siete categorías para facilitar la lectura.','0–4: primera infancia; 5: transición previa a primaria; 6–11: seis edades aproximadas de primaria; 12–17: seis edades aproximadas de secundaria; 18–24: juventud; 25–59: adultez; 60+: envejecimiento.','Son cortes analíticos. Las edades 6–11 y 12–17 aproximan ciclos educativos por edad, pero no asignan grado ni demuestran asistencia.'],
   'Population by age groups':['Groups single-year ages into seven categories for easier reading.','0–4: early childhood; 5: transition before primary; 6–11: six approximate primary ages; 12–17: six approximate secondary ages; 18–24: youth; 25–59: adulthood; 60+: ageing.','These are analytical cut-offs. Ages 6–11 and 12–17 approximate education-cycle ages but do not assign grade or prove attendance.'],
   'Razón de masculinidad por territorio':['Compara el número de hombres con el de mujeres en cada territorio.','Para cada territorio: hombres ÷ mujeres × 100.','100 significa igual número; 105 significa 105 hombres por cada 100 mujeres; 95 significa 95 hombres por cada 100 mujeres.'],
   'Sex ratio by territory':['Compares the number of men with the number of women in each territory.','For each territory: men ÷ women × 100.','100 means equal numbers; 105 means 105 men per 100 women; 95 means 95 men per 100 women.']
  };

  function findDef(label, arr){for(const [rx,v] of arr)if(rx.test(label))return v;return null}
  function box(def, compact=false){if(!def)return '';const K=isEN()?['What it means','How it is calculated','How to read it']:['Qué significa','Cómo se obtiene','Cómo leerlo'];return '<div class="plain-explain '+(compact?'compact':'')+'">'+def.map((v,i)=>'<div class="ex-row"><div class="ex-key">'+K[i]+'</div><div class="ex-value">'+v+'</div></div>').join('')+'</div>'}

  function enhance(){
    const top=document.querySelector('.topright .lang-toggle'); if(top)top.remove();
    const pi=document.getElementById('pageintro');
    if(pi && !pi.querySelector('.simple-intro')){
      const d=document.createElement('div');d.className='simple-intro';
      d.innerHTML=isEN()?'<strong>Simple reading rule.</strong> Population and ages come from the 2024 Population and Housing Census. School and enrolment figures come from the integrated education información and are a different statistical source. Every indicator below explains what it means, how it is calculated and how it should be read.':'<strong>Regla sencilla de lectura.</strong> La población, las edades y los indicadores territoriales del dashboard se presentan con referencia al <i>Censo de Población y Vivienda 2024 (CPV 2024)</i>. Debajo de cada indicador se explica qué significa, cómo se calcula y cómo debe leerse.';
      pi.appendChild(d);
    }
    const filters=document.querySelector('.filters');
    if(filters && !filters.querySelector('.filter-help')){
      const p=document.createElement('div');p.className='filter-help';
      p.innerHTML=isEN()?'<b>How filters work:</b> Department, province and municipality/TIOC narrow the census territory. The area filter uses the rural/urban classification of the locality/community; for education records, “without area classification” means the associated-community area field is not usable as Rural or Urban. It does <b>not</b> mean that the school lacks a geographic location. TIOC means Indigenous Native Peasant Territory.':'<b>Cómo funcionan los filtros:</b> Departamento, provincia y municipio/TIOC reducen el territorio censal mostrado. El filtro de área utiliza la clasificación rural/urbana de la localidad o comunidad; en los registros educativos, “UE sin clasificación de área” significa que el campo de área de la comunidad asociada no permite clasificarla como Rural o Urbana. <b>No</b> significa que la UE carezca de ubicación geográfica. TIOC significa Territorio Indígena Originario Campesino.';
      filters.appendChild(p);
    }
    document.querySelectorAll('#contents .kpi').forEach(k=>{
      if(k.dataset.simpleExplained)return;const lab=normalize(k.querySelector('.kpi-label')?.textContent);const def=findDef(lab,isEN()?kpiEN:kpiES);if(def){k.insertAdjacentHTML('beforeend',box(def,true));k.dataset.simpleExplained='1';}
    });
    document.querySelectorAll('#contents .card').forEach(c=>{
      if(c.dataset.simpleExplained)return;const title=normalize(c.querySelector('.card-title')?.textContent);const def=cards[title];if(def){const rg=c.querySelector(':scope > .reading-guide');if(rg)rg.insertAdjacentHTML('beforebegin',box(def,false));else c.insertAdjacentHTML('beforeend',box(def,false));c.dataset.simpleExplained='1';}
    });
    document.querySelectorAll('.reading-guide .guide-label').forEach(el=>{
      const t=normalize(el.textContent);
      if(isEN()){if(t==='Interpretation')el.textContent='How to read it';if(t==='Caution')el.textContent='Important';if(t==='See also')el.textContent='Related view';}
      else {if(t==='Interpretación')el.textContent='Cómo leerlo';if(t==='Precaución')el.textContent='Importante';if(t==='Ver también')el.textContent='Vista relacionada';}
    });
  }
  function start(){enhance();const root=document.querySelector('.main')||document.body;new MutationObserver(()=>requestAnimationFrame(enhance)).observe(root,{childList:true,subtree:true});setInterval(enhance,1200)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
