param(
  [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
)
$ErrorActionPreference = 'Stop'
$culture = [System.Globalization.CultureInfo]::InvariantCulture
Add-Type -AssemblyName System.Drawing
$outDir = Join-Path $ProjectRoot 'outputs\figures\oecd_style'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$dataPath = Join-Path $ProjectRoot 'data\processed\dashboard_panel.csv'
$coefPath = Join-Path $ProjectRoot 'outputs\models\stage1_coefficients.csv'
$samplePath = Join-Path $ProjectRoot 'outputs\models\stage1_analytic_sample.csv'
$data = Import-Csv $dataPath
$coef = Import-Csv $coefPath
$sample = Import-Csv $samplePath
function N($x){ if($null -eq $x){ return $null }; $s=[string]$x; if([string]::IsNullOrWhiteSpace($s) -or $s -eq 'NA'){ return $null }; try { return [double]::Parse($s,$culture) } catch { return $null } }
function F($x,[int]$d=2){ if($null -eq $x){ return '' }; return ([double]$x).ToString('F'+$d,$culture) }
function Esc($s){ return [System.Security.SecurityElement]::Escape([string]$s) }
function Mean($vals){ $v=@($vals | Where-Object { $null -ne $_ }); if($v.Count -eq 0){ return $null }; return (($v | Measure-Object -Average).Average) }
function Corr($x,$y){ $pairs=@(); for($i=0;$i -lt $x.Count;$i++){ if($null -ne $x[$i] -and $null -ne $y[$i]){ $pairs += ,@($x[$i],$y[$i]) } }; if($pairs.Count -le 2){ return $null }; $mx=Mean ($pairs | ForEach-Object { $_[0] }); $my=Mean ($pairs | ForEach-Object { $_[1] }); $num=0.0; $dx=0.0; $dy=0.0; foreach($p in $pairs){ $a=$p[0]-$mx; $b=$p[1]-$my; $num += $a*$b; $dx += $a*$a; $dy += $b*$b }; if($dx -eq 0 -or $dy -eq 0){ return $null }; return $num/[Math]::Sqrt($dx*$dy) }
function FitLine($rows,$xvar,$yvar){ $pairs=@(); foreach($r in $rows){ $x=N $r.$xvar; $y=N $r.$yvar; if($null -ne $x -and $null -ne $y){ $pairs += ,@($x,$y) } }; if($pairs.Count -lt 3){ return $null }; $mx=Mean ($pairs | ForEach-Object { $_[0] }); $my=Mean ($pairs | ForEach-Object { $_[1] }); $num=0.0; $den=0.0; foreach($p in $pairs){ $num += ($p[0]-$mx)*($p[1]-$my); $den += [Math]::Pow($p[0]-$mx,2) }; if($den -eq 0){ return $null }; $b=$num/$den; $a=$my-$b*$mx; return @{a=$a;b=$b} }
function Range($vals,[double]$pad=0.08){ $pad=[double]$pad; $nums=New-Object System.Collections.Generic.List[double]; foreach($item in @($vals)){ if($null -eq $item){ continue }; if($item -is [array]){ foreach($sub in $item){ if($null -ne $sub){ $nums.Add([double]$sub) } } } else { $nums.Add([double]$item) } }; if($nums.Count -eq 0){ return @(0,1) }; $mn=[double]::PositiveInfinity; $mx=[double]::NegativeInfinity; foreach($n in $nums.ToArray()){ if($n -lt $mn){ $mn=[double]$n }; if($n -gt $mx){ $mx=[double]$n } }; if($mn -eq $mx){ $mn-=1; $mx+=1 }; $p=[double](([double]($mx-$mn))*$pad); $lo=[double]$mn - $p; $hi=[double]$mx + $p; return @($lo,$hi) }
function SvgStart($w,$h,$title,$subtitle){ @("<svg xmlns='http://www.w3.org/2000/svg' width='$w' height='$h' viewBox='0 0 $w $h'>","<rect width='100%' height='100%' fill='#FFFFFF'/>","<text x='56' y='58' font-family='Arial, Helvetica, sans-serif' font-size='30' font-weight='700' fill='#12355B'>$(Esc $title)</text>","<text x='56' y='90' font-family='Arial, Helvetica, sans-serif' font-size='17' fill='#6B7280'>$(Esc $subtitle)</text>") }
function SvgEnd($note){ @("<text x='56' y='950' font-family='Arial, Helvetica, sans-serif' font-size='13' fill='#6B7280'>$(Esc $note)</text>","</svg>") }
function Color($hex){ [System.Drawing.ColorTranslator]::FromHtml($hex) }
function Font([float]$size, $style=[System.Drawing.FontStyle]::Regular){ New-Object System.Drawing.Font -ArgumentList @('Arial',$size,$style) }
function Pen($hex,[float]$w=1){ New-Object System.Drawing.Pen -ArgumentList @((Color $hex),$w) }
function Brush($hex){ New-Object System.Drawing.SolidBrush -ArgumentList @((Color $hex)) }
function SavePng($file,$title,$subtitle,[scriptblock]$draw,$note='Source: harmonized country-year panel.'){ $bmp=New-Object System.Drawing.Bitmap 1600,1000; $g=[System.Drawing.Graphics]::FromImage($bmp); $g.SmoothingMode='AntiAlias'; $g.Clear((Color '#FFFFFF')); $titleFont=Font 28 ([System.Drawing.FontStyle]::Bold); $subFont=Font 16; $noteFont=Font 11; $g.DrawString($title,$titleFont,(Brush '#12355B'),56,42); $g.DrawString($subtitle,$subFont,(Brush '#6B7280'),56,82); & $draw $g; $g.DrawString($note,$noteFont,(Brush '#6B7280'),56,950); $bmp.Save($file,[System.Drawing.Imaging.ImageFormat]::Png); $g.Dispose(); $bmp.Dispose() }
function DrawLegend($g,$items,$x,$y){ $font=Font 11; $offset=0; foreach($it in $items){ $b=Brush $it.color; $g.FillRectangle($b,$x+$offset,$y+3,22,8); $g.DrawString($it.label,$font,(Brush '#374151'),$x+$offset+30,$y-2); $offset += 205 } }
function SaveSvg($name,$lines){ [IO.File]::WriteAllLines((Join-Path $outDir $name),[string[]]$lines,[Text.UTF8Encoding]::new($false)) }
# 1 Ranking
$latest = foreach($grp in ($data | Group-Object iso3)){ $rows=@($grp.Group | Where-Object { $null -ne (N $_.structural_vulnerability_index) } | Sort-Object { [int]$_.year } -Descending); if($rows.Count){ $rows[0] } }
$rank=@($latest | Sort-Object { -(N $_.structural_vulnerability_index) } | Select-Object -First 15)
$w=1600;$h=1000;$left=360;$right=110;$top=145;$barH=38;$gap=15;$plotW=$w-$left-$right;$max=(($rank | ForEach-Object { N $_.structural_vulnerability_index }) | Measure-Object -Maximum).Maximum
$svg=SvgStart $w $h 'Structural Vulnerability Ranking in Latin America and the Caribbean' 'Latest available country-year observations from the harmonized panel'
for($i=0;$i -lt $rank.Count;$i++){ $r=$rank[$rank.Count-1-$i]; $v=N $r.structural_vulnerability_index; $y=$top+$i*($barH+$gap); $bw=($v/$max)*$plotW; $fill=if($r.iso3 -eq 'BOL'){'#8A7650'}else{'#12355B'}; $svg += "<text x='56' y='$($y+25)' font-family='Arial, Helvetica, sans-serif' font-size='15' fill='#1F2937'>$(Esc $r.country_name)</text>"; $svg += "<rect x='$left' y='$y' width='$bw' height='$barH' rx='2' fill='$fill'/>"; $svg += "<text x='$($left+$bw+10)' y='$($y+25)' font-family='Arial, Helvetica, sans-serif' font-size='14' fill='#6B7280'>$(F $v 2)</text>" }
$svg += "<line x1='$left' x2='$left' y1='$($top-10)' y2='$($top+$rank.Count*($barH+$gap)-$gap+8)' stroke='#D1D5DB'/>"
$svg += SvgEnd 'Higher values indicate greater structural vulnerability. Source: harmonized country-year panel.'
SaveSvg 'figure_01_structural_vulnerability_ranking.svg' $svg
SavePng (Join-Path $outDir 'figure_01_structural_vulnerability_ranking.png') 'Structural Vulnerability Ranking in Latin America and the Caribbean' 'Latest available country-year observations from the harmonized panel' { param($g) $font=Font 13; $lab=Font 14; for($i=0;$i -lt $rank.Count;$i++){ $r=$rank[$rank.Count-1-$i]; $v=N $r.structural_vulnerability_index; $y=$top+$i*($barH+$gap); $bw=($v/$max)*$plotW; $g.DrawString($r.country_name,$lab,(Brush '#1F2937'),56,$y+7); $g.FillRectangle((Brush ($(if($r.iso3 -eq 'BOL'){'#8A7650'}else{'#12355B'}))),$left,$y,$bw,$barH); $g.DrawString((F $v 2),$font,(Brush '#6B7280'),$left+$bw+10,$y+8) } $g.DrawLine((Pen '#D1D5DB'),$left,$top-10,$left,$top+$rank.Count*($barH+$gap)-$gap+8) } 'Higher values indicate greater structural vulnerability. Source: harmonized country-year panel.'
# shared line chart helper
function PolySvg($rows,$field,$xMap,$yMap,$color){ $pts=@(); foreach($r in $rows){ $v=N $r.$field; if($null -ne $v){ $pts += "$( & $xMap ([double]$r.year)),$( & $yMap $v)" } }; return "<polyline fill='none' stroke='$color' stroke-width='3.2' stroke-linecap='round' stroke-linejoin='round' points='$($pts -join ' ')'/>" }
# 2 Bolivia profile
$bol=@($data | Where-Object { $_.iso3 -eq 'BOL' } | Sort-Object { [int]$_.year })
$years=@($bol | ForEach-Object {[int]$_.year}); $xmin=($years|Measure-Object -Minimum).Minimum; $xmax=($years|Measure-Object -Maximum).Maximum
$svg=SvgStart $w $h 'Bolivia: Poverty Decline and Persistent Labor Informality' 'Country profile based on the structural vulnerability panel'
$L=105;$Right=80;$T1=145;$H1=450;$T2=680;$H2=170;$PW=$w-$L-$Right
$xFn={ param($yr) $L+(($yr-$xmin)/($xmax-$xmin))*$PW }
$yPct={ param($v) $T1+(100-$v)/100*$H1 }
$ySviRange=Range (@($bol | ForEach-Object { N $_.structural_vulnerability_index })) .12; $smin=$ySviRange[0]; $smax=$ySviRange[1]
$ySvi={ param($v) $T2+($smax-$v)/($smax-$smin)*$H2 }
foreach($tick in 0,25,50,75,100){ $yy=& $yPct $tick; $svg += "<line x1='$L' x2='$($w-$Right)' y1='$yy' y2='$yy' stroke='#E5E7EB'/><text x='58' y='$($yy+5)' font-family='Arial' font-size='12' fill='#6B7280'>$tick</text>" }
$svg += PolySvg $bol 'monetary_poverty' $xFn $yPct '#12355B'; $svg += PolySvg $bol 'labor_informality' $xFn $yPct '#8A7650'; $svg += PolySvg $bol 'social_protection_coverage' $xFn $yPct '#4F7C8A'
$svg += "<text x='$L' y='$($T1-18)' font-family='Arial' font-size='14' font-weight='700' fill='#374151'>Percent indicators</text>"
$svg += "<rect x='$L' y='$T2' width='$PW' height='$H2' fill='none' stroke='#E5E7EB'/><text x='$L' y='$($T2-18)' font-family='Arial' font-size='14' font-weight='700' fill='#374151'>Structural vulnerability index</text>"
$svg += PolySvg $bol 'structural_vulnerability_index' $xFn $ySvi '#12355B'
$svg += "<text x='105' y='900' font-family='Arial' font-size='14' fill='#12355B'>monetary poverty</text><text x='275' y='900' font-family='Arial' font-size='14' fill='#8A7650'>labor informality</text><text x='455' y='900' font-family='Arial' font-size='14' fill='#4F7C8A'>social protection</text><text x='660' y='900' font-family='Arial' font-size='14' fill='#12355B'>structural vulnerability</text>"
$svg += SvgEnd 'Source: harmonized country-year panel.'; SaveSvg 'figure_02_bolivia_profile.svg' $svg
SavePng (Join-Path $outDir 'figure_02_bolivia_profile.png') 'Bolivia: Poverty Decline and Persistent Labor Informality' 'Country profile based on the structural vulnerability panel' { param($g) foreach($tick in 0,25,50,75,100){ $yy=& $yPct $tick; $g.DrawLine((Pen '#E5E7EB'),$L,$yy,$w-$Right,$yy); $g.DrawString([string]$tick,(Font 10),(Brush '#6B7280'),58,$yy-8) } $colors=@{monetary_poverty='#12355B';labor_informality='#8A7650';social_protection_coverage='#4F7C8A'}; foreach($field in $colors.Keys){ $prev=$null; foreach($r in $bol){ $v=N $r.$field; if($null -ne $v){ $pt=New-Object System.Drawing.PointF ([float](& $xFn ([double]$r.year))),([float](& $yPct $v)); if($prev){ $g.DrawLine((Pen $colors[$field] 3),$prev,$pt) }; $prev=$pt } } }; $prev=$null; foreach($r in $bol){ $v=N $r.structural_vulnerability_index; if($null -ne $v){ $pt=New-Object System.Drawing.PointF ([float](& $xFn ([double]$r.year))),([float](& $ySvi $v)); if($prev){ $g.DrawLine((Pen '#12355B' 3),$prev,$pt) }; $prev=$pt } }; $g.DrawRectangle((Pen '#E5E7EB'),$L,$T2,$PW,$H2); DrawLegend $g @(@{label='monetary poverty';color='#12355B'},@{label='labor informality';color='#8A7650'},@{label='social protection';color='#4F7C8A'},@{label='structural vulnerability';color='#12355B'}) 105 900 } 
# 3 Regional trends
$allYears=@($data | ForEach-Object {[int]$_.year} | Sort-Object -Unique)
$trends=foreach($y in $allYears){ $rows=@($data | Where-Object {[int]$_.year -eq $y}); [pscustomobject]@{year=$y; monetary_poverty=Mean (@($rows|ForEach-Object{N $_.monetary_poverty})); labor_informality=Mean (@($rows|ForEach-Object{N $_.labor_informality})); social_protection_coverage=Mean (@($rows|ForEach-Object{N $_.social_protection_coverage})); unemployment=Mean (@($rows|ForEach-Object{N $_.unemployment}))} }
$xmin=($allYears|Measure-Object -Minimum).Minimum; $xmax=($allYears|Measure-Object -Maximum).Maximum; $L=105;$Right=80;$T=145;$Hc=680;$PW=$w-$L-$Right
$xFn={ param($yr) $L+(($yr-$xmin)/($xmax-$xmin))*$PW }; $yFn={ param($v) $T+(100-$v)/100*$Hc }
$svg=SvgStart $w $h 'Regional Trends in Poverty, Informality, Social Protection, and Unemployment' 'Annual averages across available country-year observations'
foreach($tick in 0,25,50,75,100){ $yy=& $yFn $tick; $svg += "<line x1='$L' x2='$($w-$Right)' y1='$yy' y2='$yy' stroke='#E5E7EB'/><text x='58' y='$($yy+5)' font-family='Arial' font-size='12' fill='#6B7280'>$tick</text>" }
$svg += PolySvg $trends 'monetary_poverty' $xFn $yFn '#12355B'; $svg += PolySvg $trends 'labor_informality' $xFn $yFn '#8A7650'; $svg += PolySvg $trends 'social_protection_coverage' $xFn $yFn '#4F7C8A'; $svg += PolySvg $trends 'unemployment' $xFn $yFn '#6B7280'
$svg += "<text x='105' y='875' font-family='Arial' font-size='14' fill='#12355B'>poverty</text><text x='205' y='875' font-family='Arial' font-size='14' fill='#8A7650'>informality</text><text x='330' y='875' font-family='Arial' font-size='14' fill='#4F7C8A'>social protection</text><text x='500' y='875' font-family='Arial' font-size='14' fill='#6B7280'>unemployment</text>"
$svg += SvgEnd 'Source: harmonized country-year panel. Averages use available observations.'; SaveSvg 'figure_03_lac_average_trends.svg' $svg
SavePng (Join-Path $outDir 'figure_03_lac_average_trends.png') 'Regional Trends in Poverty, Informality, Social Protection, and Unemployment' 'Annual averages across available country-year observations' { param($g) foreach($tick in 0,25,50,75,100){ $yy=& $yFn $tick; $g.DrawLine((Pen '#E5E7EB'),$L,$yy,$w-$Right,$yy); $g.DrawString([string]$tick,(Font 10),(Brush '#6B7280'),58,$yy-8) } $colors=@{monetary_poverty='#12355B';labor_informality='#8A7650';social_protection_coverage='#4F7C8A';unemployment='#6B7280'}; foreach($field in $colors.Keys){ $prev=$null; foreach($r in $trends){ $v=N $r.$field; if($null -ne $v){ $pt=New-Object System.Drawing.PointF ([float](& $xFn ([double]$r.year))),([float](& $yFn $v)); if($prev){ $g.DrawLine((Pen $colors[$field] 3),$prev,$pt) }; $prev=$pt } } }; DrawLegend $g @(@{label='poverty';color='#12355B'},@{label='informality';color='#8A7650'},@{label='social protection';color='#4F7C8A'},@{label='unemployment';color='#6B7280'}) 105 875 } 'Source: harmonized country-year panel. Averages use available observations.'
# 4 Correlation heatmap
$vars=@('monetary_poverty','extreme_poverty','labor_informality','social_protection_coverage','gdp_per_capita','unemployment','gini','structural_vulnerability_index')
function CorrFill($v){ if($null -eq $v){return '#F3F4F6'}; if($v -ge 0){ $t=[Math]::Min(1,[Math]::Abs($v)); $r=[int](247+(18-247)*$t); $g=[int](248+(53-248)*$t); $b=[int](250+(91-250)*$t) } else { $t=[Math]::Min(1,[Math]::Abs($v)); $r=[int](247+(138-247)*$t); $g=[int](248+(118-248)*$t); $b=[int](250+(80-250)*$t) }; return ('#{0:X2}{1:X2}{2:X2}' -f $r,$g,$b) }
$cell=95;$L=405;$T=185
$svg=SvgStart $w $h 'Correlation Structure of Development and Vulnerability Indicators' 'Pairwise correlations among core variables'
for($i=0;$i -lt $vars.Count;$i++){ $svg += "<text x='70' y='$($T+$i*$cell+58)' font-family='Arial' font-size='13' fill='#1F2937'>$(Esc $vars[$i])</text>"; $svg += "<text x='$($L+$i*$cell+8)' y='$($T-18)' transform='rotate(-45 $($L+$i*$cell+8),$($T-18))' font-family='Arial' font-size='13' fill='#1F2937'>$(Esc $vars[$i])</text>"; for($j=0;$j -lt $vars.Count;$j++){ $a=$vars[$i]; $b=$vars[$j]; $cv=Corr (@($data|ForEach-Object{N $_.$a})) (@($data|ForEach-Object{N $_.$b})); $fill=CorrFill $cv; $x=$L+$j*$cell; $y=$T+$i*$cell; $svg += "<rect x='$x' y='$y' width='$cell' height='$cell' fill='$fill' stroke='#FFFFFF'/><text x='$($x+30)' y='$($y+55)' font-family='Arial' font-size='15' font-weight='700' fill='#FFFFFF'>$(F $cv 2)</text>" } }
$svg += SvgEnd 'Pairwise correlations computed using available observations. Source: harmonized country-year panel.'; SaveSvg 'figure_04_correlation_heatmap.svg' $svg
SavePng (Join-Path $outDir 'figure_04_correlation_heatmap.png') 'Correlation Structure of Development and Vulnerability Indicators' 'Pairwise correlations among core variables' { param($g) $font=Font 11; $num=Font 13 ([System.Drawing.FontStyle]::Bold); for($i=0;$i -lt $vars.Count;$i++){ $g.DrawString($vars[$i],$font,(Brush '#1F2937'),70,$T+$i*$cell+38); for($j=0;$j -lt $vars.Count;$j++){ $a=$vars[$i]; $b=$vars[$j]; $cv=Corr (@($data|ForEach-Object{N $_.$a})) (@($data|ForEach-Object{N $_.$b})); $x=$L+$j*$cell; $y=$T+$i*$cell; $g.FillRectangle((Brush (CorrFill $cv)),$x,$y,$cell,$cell); $g.DrawRectangle((Pen '#FFFFFF'),$x,$y,$cell,$cell); $g.DrawString((F $cv 2),$num,(Brush '#FFFFFF'),$x+24,$y+37) } } } 'Pairwise correlations computed using available observations. Source: harmonized country-year panel.'
# Scatter helper
function MakeScatter($name,$title,$subtitle,$xvar,$yvar,$xlabel,$ylabel,$labelExtreme){ $rows=@($data | Where-Object { $null -ne (N $_.$xvar) -and $null -ne (N $_.$yvar) }); $xr=Range (@($rows|ForEach-Object{N $_.$xvar})) .08; $yr=Range (@($rows|ForEach-Object{N $_.$yvar})) .08; $L=120;$Right=90;$T=155;$Hc=665;$PW=$w-$L-$Right; $xMap={ param($v) $L+($v-$xr[0])/($xr[1]-$xr[0])*$PW }; $yMap={ param($v) $T+($yr[1]-$v)/($yr[1]-$yr[0])*$Hc }; $fit=FitLine $rows $xvar $yvar; $svg=SvgStart $w $h $title $subtitle; for($i=0;$i -le 4;$i++){ $yy=$T+$i*$Hc/4; $svg += "<line x1='$L' x2='$($w-$Right)' y1='$yy' y2='$yy' stroke='#E5E7EB'/>" }; foreach($r in $rows){ $x=& $xMap (N $r.$xvar); $y=& $yMap (N $r.$yvar); $svg += "<circle cx='$x' cy='$y' r='4.3' fill='#12355B' opacity='0.38'/>" }; if($fit){ $x1=$xr[0]; $x2=$xr[1]; $y1=$fit.a+$fit.b*$x1; $y2=$fit.a+$fit.b*$x2; $svg += "<line x1='$( & $xMap $x1)' y1='$( & $yMap $y1)' x2='$( & $xMap $x2)' y2='$( & $yMap $y2)' stroke='#8A7650' stroke-width='4'/>" }; if($labelExtreme){ $latestByCountry=foreach($grp in ($rows|Group-Object iso3)){ @($grp.Group|Sort-Object {[int]$_.year} -Descending)[0] }; $labels=@($latestByCountry|Sort-Object { -(N $_.$yvar) }|Select-Object -First 3); $bolLatest=@($latestByCountry|Where-Object {$_.iso3 -eq 'BOL'}|Select-Object -First 1); if($bolLatest){ $labels += $bolLatest }; foreach($r in ($labels|Sort-Object iso3 -Unique)){ $svg += "<text x='$(( & $xMap (N $r.$xvar))+8)' y='$(( & $yMap (N $r.$yvar))-8)' font-family='Arial' font-size='13' fill='#374151'>$(Esc $r.iso3)</text>" } }; $svg += "<text x='$($w/2-120)' y='875' font-family='Arial' font-size='15' fill='#374151'>$(Esc $xlabel)</text><text x='30' y='500' transform='rotate(-90 30,500)' font-family='Arial' font-size='15' fill='#374151'>$(Esc $ylabel)</text>"; $svg += SvgEnd 'Source: harmonized country-year panel.'; SaveSvg ($name+'.svg') $svg; SavePng (Join-Path $outDir ($name+'.png')) $title $subtitle { param($g) for($i=0;$i -le 4;$i++){ $yy=$T+$i*$Hc/4; $g.DrawLine((Pen '#E5E7EB'),$L,$yy,$w-$Right,$yy) }; foreach($r in $rows){ $g.FillEllipse((Brush '#12355B'),(& $xMap (N $r.$xvar))-4,(& $yMap (N $r.$yvar))-4,8,8) }; if($fit){ $x1=$xr[0]; $x2=$xr[1]; $y1=$fit.a+$fit.b*$x1; $y2=$fit.a+$fit.b*$x2; $g.DrawLine((Pen '#8A7650' 4),(& $xMap $x1),(& $yMap $y1),(& $xMap $x2),(& $yMap $y2)) } } }
MakeScatter 'figure_05_scatter_informality_vulnerability' 'Labor Informality and Structural Vulnerability' 'Country-year relationship across Latin America and the Caribbean' 'labor_informality' 'structural_vulnerability_index' 'Labor informality' 'Structural Vulnerability Index' $true
MakeScatter 'figure_06_scatter_social_protection_vulnerability' 'Social Protection Coverage and Structural Vulnerability' 'Descriptive association using available country-year observations' 'social_protection_coverage' 'structural_vulnerability_index' 'Social protection coverage' 'Structural Vulnerability Index' $false
# 7 Coefficients
$terms=@('labor_informality','social_protection_coverage','gdp_per_capita_1000','unemployment','gini'); $coefRows=@($coef|Where-Object {$_.model_id -eq 'model3' -and $terms -contains $_.term}); $vals=@(); foreach($r in $coefRows){ $vals += N $r.conf_low; $vals += N $r.conf_high }; $xr=Range $vals .12; $L=430;$R=100;$T=185;$rowH=105;$PW=$w-$L-$Right; $xMap={ param($v) $L+($v-$xr[0])/($xr[1]-$xr[0])*$PW }
$svg=SvgStart $w $h 'Two-Way Fixed Effects Estimates' 'Dependent variable: Structural Vulnerability Index'
$zero=& $xMap 0; $svg += "<line x1='$zero' x2='$zero' y1='$($T-40)' y2='$($T+$coefRows.Count*$rowH)' stroke='#9CA3AF' stroke-dasharray='6 6'/>"
for($i=0;$i -lt $coefRows.Count;$i++){ $r=$coefRows[$i]; $y=$T+$i*$rowH; $est=N $r.estimate; $lo=N $r.conf_low; $hi=N $r.conf_high; $svg += "<text x='56' y='$($y+8)' font-family='Arial' font-size='17' fill='#1F2937'>$(Esc $r.term)</text><line x1='$( & $xMap $lo)' x2='$( & $xMap $hi)' y1='$y' y2='$y' stroke='#12355B' stroke-width='4'/><circle cx='$( & $xMap $est)' cy='$y' r='8' fill='#8A7650'/><text x='$(( & $xMap $hi)+12)' y='$($y+5)' font-family='Arial' font-size='13' fill='#6B7280'>$(F $est 4)</text>" }
$svg += SvgEnd 'Intervals use existing clustered standard errors from stage1_coefficients.csv.'; SaveSvg 'figure_07_model_coefficients.svg' $svg
SavePng (Join-Path $outDir 'figure_07_model_coefficients.png') 'Two-Way Fixed Effects Estimates' 'Dependent variable: Structural Vulnerability Index' { param($g) $g.DrawLine((Pen '#9CA3AF'),$zero,$T-40,$zero,$T+$coefRows.Count*$rowH); $font=Font 15; $small=Font 11; for($i=0;$i -lt $coefRows.Count;$i++){ $r=$coefRows[$i]; $y=$T+$i*$rowH; $est=N $r.estimate; $lo=N $r.conf_low; $hi=N $r.conf_high; $g.DrawString($r.term,$font,(Brush '#1F2937'),56,$y-18); $g.DrawLine((Pen '#12355B' 4),(& $xMap $lo),$y,(& $xMap $hi),$y); $g.FillEllipse((Brush '#8A7650'),(& $xMap $est)-8,$y-8,16,16); $g.DrawString((F $est 4),$small,(Brush '#6B7280'),(& $xMap $hi)+12,$y-8) } } 'Intervals use existing clustered standard errors from stage1_coefficients.csv.'
# 8 Predicted vs observed from existing coefficients
$cm=@{}; foreach($r in ($coef|Where-Object {$_.model_id -eq 'model3'})){ $cm[$r.term]=N $r.estimate }
$predRows=foreach($r in $sample){ $p=$cm['Intercept']; foreach($t in @('labor_informality','social_protection_coverage','gdp_per_capita_1000','unemployment','gini')){ $p += $cm[$t]*(N $r.$t) }; $ct='country_fe_'+$r.iso3; if($cm.ContainsKey($ct)){ $p += $cm[$ct] }; $yt='year_fe_'+$r.year; if($cm.ContainsKey($yt)){ $p += $cm[$yt] }; [pscustomobject]@{observed=N $r.dependent; predicted=$p; iso3=$r.iso3; year=$r.year} }
$vals=@(); foreach($r in $predRows){$vals+=$r.observed;$vals+=$r.predicted}; $rr=Range $vals .08; $L=120;$Right=90;$T=155;$Hc=665;$PW=$w-$L-$Right; $xMap={ param($v) $L+($v-$rr[0])/($rr[1]-$rr[0])*$PW }; $yMap={ param($v) $T+($rr[1]-$v)/($rr[1]-$rr[0])*$Hc }
$svg=SvgStart $w $h 'Observed and Predicted Structural Vulnerability' 'Model diagnostic for the two-way fixed effects specification'; $svg += "<line x1='$( & $xMap $rr[0])' y1='$( & $yMap $rr[0])' x2='$( & $xMap $rr[1])' y2='$( & $yMap $rr[1])' stroke='#8A7650' stroke-width='4'/>"; foreach($r in $predRows){ $svg += "<circle cx='$( & $xMap $r.observed)' cy='$( & $yMap $r.predicted)' r='4.4' fill='#12355B' opacity='0.42'/>" }; $svg += "<text x='630' y='875' font-family='Arial' font-size='15' fill='#374151'>Observed</text><text x='30' y='500' transform='rotate(-90 30,500)' font-family='Arial' font-size='15' fill='#374151'>Predicted</text>"; $svg += SvgEnd 'Predictions are computed from already-estimated TWFE coefficients.'; SaveSvg 'figure_08_predicted_vs_observed.svg' $svg
SavePng (Join-Path $outDir 'figure_08_predicted_vs_observed.png') 'Observed and Predicted Structural Vulnerability' 'Model diagnostic for the two-way fixed effects specification' { param($g) $g.DrawLine((Pen '#8A7650' 4),(& $xMap $rr[0]),(& $yMap $rr[0]),(& $xMap $rr[1]),(& $yMap $rr[1])); foreach($r in $predRows){ $g.FillEllipse((Brush '#12355B'),(& $xMap $r.observed)-4,(& $yMap $r.predicted)-4,8,8) } } 'Predictions are computed from already-estimated TWFE coefficients.'
# 9 Missingness map
$varsMiss=$vars; $yearsAll=@($data|ForEach-Object{[int]$_.year}|Sort-Object -Unique); $cellW=50;$cellH=55;$L=300;$T=170
function MissFill($m){ $t=[Math]::Min(1,[Math]::Max(0,$m)); $r=[int](247+(18-247)*$t); $g=[int](248+(53-248)*$t); $b=[int](250+(91-250)*$t); return ('#{0:X2}{1:X2}{2:X2}' -f $r,$g,$b) }
$svg=SvgStart $w $h 'Indicator Coverage and Missingness' 'Data availability across the country-year panel'
for($i=0;$i -lt $varsMiss.Count;$i++){ $v=$varsMiss[$i]; $svg += "<text x='56' y='$($T+$i*$cellH+35)' font-family='Arial' font-size='13' fill='#1F2937'>$(Esc $v)</text>"; for($j=0;$j -lt $yearsAll.Count;$j++){ $y=$yearsAll[$j]; $rows=@($data|Where-Object{[int]$_.year -eq $y}); $miss=(@($rows|Where-Object{ $null -eq (N $_.$v) })).Count/[double]$rows.Count; $svg += "<rect x='$($L+$j*$cellW)' y='$($T+$i*$cellH)' width='$cellW' height='$cellH' fill='$(MissFill $miss)' stroke='#FFFFFF'/>" } }
for($j=0;$j -lt $yearsAll.Count;$j+=2){ $svg += "<text x='$($L+$j*$cellW+8)' y='$($T-18)' transform='rotate(-45 $($L+$j*$cellW+8),$($T-18))' font-family='Arial' font-size='12' fill='#6B7280'>$($yearsAll[$j])</text>" }
$svg += SvgEnd 'Darker cells indicate a higher missing share for that indicator-year.'; SaveSvg 'figure_09_missingness_map.svg' $svg
SavePng (Join-Path $outDir 'figure_09_missingness_map.png') 'Indicator Coverage and Missingness' 'Data availability across the country-year panel' { param($g) $font=Font 11; for($i=0;$i -lt $varsMiss.Count;$i++){ $v=$varsMiss[$i]; $g.DrawString($v,$font,(Brush '#1F2937'),56,$T+$i*$cellH+20); for($j=0;$j -lt $yearsAll.Count;$j++){ $y=$yearsAll[$j]; $rows=@($data|Where-Object{[int]$_.year -eq $y}); $miss=(@($rows|Where-Object{ $null -eq (N $_.$v) })).Count/[double]$rows.Count; $g.FillRectangle((Brush (MissFill $miss)),$L+$j*$cellW,$T+$i*$cellH,$cellW,$cellH); $g.DrawRectangle((Pen '#FFFFFF'),$L+$j*$cellW,$T+$i*$cellH,$cellW,$cellH) } } }
# 10 Pipeline
$steps=@('Research Question','Country-Year Panel','Exploratory Data Analysis','Structural Vulnerability Index','Panel Econometrics','Interpretation','Policy Implications','Paper and Dashboard')
$svg=SvgStart $w $h 'Research Pipeline' 'From research question to paper-ready interpretation and dashboard communication'
$boxW=520;$boxH=58;$x=($w-$boxW)/2;$y0=145;$gap=32
for($i=0;$i -lt $steps.Count;$i++){ $y=$y0+$i*($boxH+$gap); $svg += "<rect x='$x' y='$y' width='$boxW' height='$boxH' rx='4' fill='#FFFFFF' stroke='#D1D5DB'/><text x='$($x+32)' y='$($y+37)' font-family='Arial' font-size='18' font-weight='700' fill='#12355B'>$(Esc $steps[$i])</text>"; if($i -lt $steps.Count-1){ $svg += "<line x1='$($w/2)' y1='$($y+$boxH)' x2='$($w/2)' y2='$($y+$boxH+$gap-8)' stroke='#8A7650' stroke-width='2'/><path d='M $($w/2-7) $($y+$boxH+$gap-8) L $($w/2+7) $($y+$boxH+$gap-8) L $($w/2) $($y+$boxH+$gap+4) Z' fill='#8A7650'/>" } }
$svg += SvgEnd 'Workflow diagram for the research repository.'; SaveSvg 'figure_10_research_pipeline.svg' $svg
SavePng (Join-Path $outDir 'figure_10_research_pipeline.png') 'Research Pipeline' 'From research question to paper-ready interpretation and dashboard communication' { param($g) $font=Font 16 ([System.Drawing.FontStyle]::Bold); for($i=0;$i -lt $steps.Count;$i++){ $y=$y0+$i*($boxH+$gap); $g.FillRectangle((Brush '#FFFFFF'),$x,$y,$boxW,$boxH); $g.DrawRectangle((Pen '#D1D5DB'),$x,$y,$boxW,$boxH); $g.DrawString($steps[$i],$font,(Brush '#12355B'),$x+32,$y+16); if($i -lt $steps.Count-1){ $g.DrawLine((Pen '#8A7650' 2),$w/2,$y+$boxH,$w/2,$y+$boxH+$gap-8) } } } 'Workflow diagram for the research repository.'
Write-Host "OECD-style figures written to $outDir"










