const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'../..'),out=path.join(require('os').tmpdir(),'educacion-gasto-social-qa');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'};
const server=http.createServer((req,res)=>{let p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root)){res.writeHead(403);return res.end()}if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',types[path.extname(p)]||'application/octet-stream');fs.createReadStream(p).pipe(res)});
fs.mkdirSync(out,{recursive:true});const results=[];
async function run(name,fn){try{await fn();results.push({test:name,status:'passed'});console.log('PASS '+name)}catch(e){results.push({test:name,status:'failed',error:e.message});console.log('FAIL '+name+' '+e.message)}}
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.QA_BASE||'http://127.0.0.1:8765/';
const go=async p=>{await page.goto(base+p,{waitUntil:'networkidle',timeout:60000})};
const download=async (locator,folder)=>{const promise=page.waitForEvent('download',{timeout:15000});await locator.click();const d=await promise;const target=path.join(root,'datos',folder,d.suggestedFilename());await d.saveAs(target);assert(fs.statSync(target).size>40);return target};
await run('Portal: búsqueda, acentos y estado vacío',async()=>{await go('index.html');await page.locator('#buscar').fill('diploma');assert.equal(await page.locator('.card:visible').count(),1);await page.locator('#buscar').fill('evaluacion');assert.equal(await page.locator('.card:visible').count(),1);await page.locator('#buscar').fill('xxxxxx');assert(await page.locator('#sin-resultados').isVisible());await page.locator('#buscar').fill('')});
await run('Productos retirados: URLs devuelven 404',async()=>{for(const url of ['dashboards/gasto-educativo-por-estudiante/index.html','presentaciones/diploma-bachiller-digital/index.html'])assert.equal((await page.request.get(base+url)).status(),404)});
await run('DDE: filtros, gráficos, reporte y CSV',async()=>{await go('dashboards/gasto-dde-2016-2025/index.html');await page.selectOption('#dep',{label:'La Paz'});await page.selectOption('#year','2020');assert((await page.locator('body').innerText()).includes('2020'));assert.equal(await page.locator('.js-plotly-plot').count(),8);const f=await download(page.getByRole('button',{name:'Exportar vista CSV'}),'gasto-dde');assert(fs.readFileSync(f,'utf8').includes('La Paz'));await page.getByRole('button',{name:'Imprimir reporte',exact:true}).click();assert(await page.getByRole('button',{name:'Volver al dashboard'}).isVisible());await page.getByRole('button',{name:'Volver al dashboard'}).click();await page.getByRole('button',{name:'Restablecer',exact:true}).click();assert.equal(await page.locator('#year').inputValue(),'2025')});
await run('DDEd: seis pestañas, búsqueda, CSV y filtros',async()=>{await go('dashboards/gasto-dded-bolivia/index.html');for(const tab of ['resumen','evolucion','municipal','composicion','datos','metodo']){await page.locator('button[data-tab="'+tab+'"]').click();await page.waitForTimeout(100)}await page.locator('button[data-tab="datos"]').click();await page.selectOption('#year','2025');await page.locator('#search').fill('Salinas');const file=await download(page.locator('#export'),'gasto-dded');assert(fs.readFileSync(file,'utf8').toLowerCase().includes('salinas'));await page.locator('#reset').click();await page.locator('button[data-tab="resumen"]').click();await page.locator('button[data-level="mun"]').click();await page.locator('#zoomIn').click();await page.locator('#zoomReset').click()});
await run('Muestra: cinco pestañas y método disponible',async()=>{await go('dashboards/muestra-educativa-bolivia/index.html');const buttons=await page.getByRole('button').allTextContents();fs.writeFileSync(path.join(out,'muestra-buttons.json'),JSON.stringify(buttons));for(const name of ['Mapas','Diseño muestral y composición','Directorio completo','Método y descargas','Resumen']){let b=page.getByRole('tab',{name,exact:true});if(!await b.count())b=page.getByRole('button',{name,exact:true});await b.click();await page.waitForTimeout(300)}assert((await page.locator('body').innerText()).includes('120'));await page.getByRole('button',{name:'Método y descargas',exact:true}).click().catch(async()=>page.getByRole('tab',{name:'Método y descargas',exact:true}).click());fs.writeFileSync(path.join(out,'muestra-method-buttons.json'),JSON.stringify(await page.getByRole('button').allTextContents()));for(const label of ['Base SEIE integrada','Excel: muestra','Resultados y metadatos','Presentación para políticas','Paquete íntegro','Metodo_de_seleccion.md','FUENTE_Y_METODO.md','LEEME.md','seleccionar_muestra.py']){await download(page.getByRole('button').filter({hasText:label}),'muestra-educativa')} });
await run('Atlas: cinco módulos, filtro y exportaciones CSV',async()=>{await go('dashboards/atlas-educacion-bolivia/index.html');for(const tab of ['resumen','territorio','demografia','educacion','explorador']){await page.locator('button[data-tab="'+tab+'"]').click();await page.waitForTimeout(200)}await page.selectOption('#dep',{index:1});await download(page.locator('#export'),'atlas-educacion');await download(page.locator('#exportUE'),'atlas-educacion');await page.locator('#reset').click();await page.locator('#methodButton').click();assert(await page.locator('dialog[open]').count()>0)});
await run('Mapas educativos: cambio de año y figura 2020',async()=>{await go('dashboards/gasto-educativo-regional/index.html');await page.selectOption('#gestion','31edu20.png');await page.locator('#mapa').evaluate(e=>e.decode());assert((await page.locator('#caption').innerText()).includes('2020'))});
await run('Ejecución sin errores JavaScript',async()=>assert.deepEqual(errors,[]));fs.writeFileSync(path.join(out,process.env.QA_BASE?'functional-live.json':'functional.json'),JSON.stringify(results,null,2));await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});

